.npmignore, CHANGELOG.md, README.md, lib/index.js, package.json, test/.env, test/.env-malformed, test/test.js
- Removed the `-e`/`--env` flags in favor of just requiring the first arg to
`env-cmd` to be the relative path to the env file
- Comments are now valid in env files using the `#`
- Empty lines in env file are now ignored
- Fixed bug env file no longer needs to end on a newline (`\n`)
- Updated changelog
- Updated package version number
=> Removed -e/--env flags, allow # comment lines in env file, bug fixes

CHANGELOG.md, README.md, lib/index.js, package.json, test/test.js
- Moved over to using regex for parsing the env file
- Added support for inline comments
- Added support for `key value` pairing file format
- Will now ignore invalid lines in env file, instead of throwing an error
- Removed old test cases
- Added more specific test cases
=> Regex for parsing, support inline comments, support `key value` format

README.md, lib/index.js, package.json, test/test.js
Hello!
I came across env-cmd when trying to hunt down a module that could source env vars from a JSON file _to the environment_ rather than merging them into `process.env` within a module as [dotenv][dotenv] and a few others do.
The impetus for this was [Apex][apex] which frustratingly only supports JSON files. It's an opinion that has some merit though on reflection. JSON dodges the crossplatform issues these files tend to have both in their content and sourcing methods. Thought this dovetailed with the goals of cross-env and env-cmd and went ahead and implemented it since it requires only some short-circuit logic.
[dotenv]: https://github.com/motdotla/dotenv
[apex]: http://apex.run/
=> Add support for JSON format

README.md, lib/index.js, test/test.js
Fixes for #12 
- Fixed a bug that caused a # symbol in the env value to be interpreted
as an inline comment
- When you want to include a # in you value, you need to wrap it in
double quotes: ENV=“some#symbol value”
=> Fix bug when including a # in the env value

lib/index.js
Fixes issue #13 
- After retrieving user set envs from a file, add the system envs back
into the envs object so that envs like PATH, etc… will exist for the
spawned command
=> Add system env vars back into the env list

README.md, lib/index.js, package.json, test/test.js
If a repository contains a `.env` example file or - in case of a private repository - a `.env` file with production values, a developer can add a local (e.g. `.env.local` file to `.gitignore`) and feed it to `env-cmd`.
So in development a custom local configuration can be used, but in production, `env-cmd` falls back to `.env`
I added the implementation, added tests and updated the readme to explain what it does.
If multiple people work on a project or dev environment is different from production,
this turned out to be an amazingly useful feature to me.
It is inspired by [localenv](https://www.npmjs.com/package/localenv)
If this feature is not welcome - I'm ok with that and would then publish it as a separate module :-)
=> ADD default .env file as a fallback

README.md, lib/index.js, test/test.js
- Removed env var format `env value` (now only `env=val` works)
- Removed inline comments from `.env` files
- Added additional warning for `.rc` files if the environment does not exist
- Updated README to be easier to read and cleaner now that there are multiple ways to use this tool
Fixes: https://github.com/toddbluhm/env-cmd/issues/12
=> Fix the # comment in env var name issue, other fixes

README.md, lib/index.js, package.json, test/test.js
Sometimes it's required to not override env variables by file and just fill envs which are not set.
=> add —no-override option

README.md, lib/index.js, test/test.js
***Breaking Change***: This changes how env file pathing works.
This PR enables the use of absolute pathing and pathing using the `~` character.
- Absolute pathing (starts with a `/`): `/some/absolute/path.env`
- Pathing using `~`: `~/starts/on/home/path.env`
- Relative pathing (starts with NO `/`): `some/relative/path.env`
or `./some/relative/path.env`
- Relative pathing and parent dirs: `../some/relative/path/one/level/up.env`
Resolves: https://github.com/toddbluhm/env-cmd/issues/29
=> Allow for using absolute pathing, ~ pathing, and relative pathing

lib/index.js, test/test.js
This feature borrows a few lines of code from [dotenv](https://github.com/motdotla/dotenv) to add support for escaping double and single quoted values. This is closer to the behavior of the shell which escapes quoted values assigned to variables.
On one of my projects, I need to specify an environment variable as a JSON string, which would break when quoted (quotes are also required to source the `.env` file in the shell). With this patch, the quoted variable now has the same value when sourced in the shell or loaded with env-cmd.
=> Add support for escaping double and single quoted values.

CHANGELOG.md, lib/index.js, test/test.js
When parsing an env var file, we need to stripe out the spaces around the `key` and `value` so as to allow a broader range of formatting and better compatibility with other env programs.
`ENV = VALUE` - result is now just `VALUE`
`ENV = " Value"` - result is now ` Value` (space in front)
Fixes issue: https://github.com/toddbluhm/env-cmd/issues/32
=> Stripe spaces out around equal sign when parsing an env file.

CHANGELOG.md, lib/index.js, package.json, test/test.js
- Implemented a broader solution to killing the parent/spawned process
that includes hooks for certain specific signals and then the generic
node exit event
- Added test cases to support the new termination solution
=> Fix bugs in parent and spawn process termination

README.md
The docs were a bit unclear about what the format of an asynchronous env file should be. Looking into the code I see that the file should export (rather than return) either an object or a Promise resolving to an object. So I updated the readme to be clearer about this.
=> Detail the expected format of async env file

README.md, dist/env-cmd.js, dist/expand-envs.d.ts, dist/expand-envs.js, dist/parse-args.js, dist/types.d.ts, src/env-cmd.ts, src/expand-envs.ts, src/parse-args.ts, src/types.ts, test/env-cmd.spec.ts, test/expand-envs.spec.ts
This pull request adds support for expanding environment variable
expansion support. Closes #91
Since the user controls the call site of cmd-env, it only supports
basic UNIX style $var format. `%var%` (windows) or `${var}` is not
supported. However, you can escape variable expansion by escaping
the dollar sign like so `\$`.
Signed-off-by: omeid matten <public@omeid.me>
=> feat: Support env vars expansion in cmd and args

dist/parse-env-file.js, dist/parse-rc-file.js, src/parse-env-file.ts, src/parse-rc-file.ts
With [ES Modules](https://blog.logrocket.com/es-modules-in-node-js-12-from-experimental-to-release/) project,in package.json:
`  
"type": "module"
`
error:
```
change the requiring code to use import(), or remove "type": "module" from package.json.
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
```
Fix allow this execution format:
```
env-cmd --rc-file .env-cmdrc.cjs -e development node .
```
=> fix: add  type module support

src/get-env-vars.ts, src/parse-rc-file.ts, test/parse-args.spec.ts
Tests currently aren't running on CI because lint is failing. This corrects linting errors in src/parse-rc-file.ts to ensure compliance with code style guidelines. It also resolves other auto-fixable lint errors.
=> fix: resolve lint issue in src/parse-rc-file.ts

dist/parse-env-file.js, src/parse-env-file.ts, test/parse-env-file.spec.ts
From #333, this updates and replaces that PR
> If you have a value containing a # followed at some point by a line containing only #\n, the wrong # will be removed by stripComments().
>This PR both fixes this issue and simplifies stripComments().
=> fix(parse-env-file): fix strip comments per PR #333

dist/parse-args.js, dist/parse-env-file.js, dist/parse-rc-file.js, dist/utils.d.ts, dist/utils.js, src/parse-args.ts, src/parse-env-file.ts, src/parse-rc-file.ts, src/utils.ts
The latest refactoring (#392) caused this library to crash for node versions `v18.0`-`v18.19` and `20.0`-`20.9`.
These versions of node don't support "[Import Attributes](https://v8.dev/features/import-attributes)" (`import ...  from ... with ...`), they only support "[Import Assertions](https://v8.dev/features/import-assertions)" (`import ...  from ... assert ...`).
---
In a follow-up PR I'll update the test suite to run the oldest version of node that we support (v18.0.0). This is non-straightforward because [esmock](https://npm.im/esmock) doesn't work well on this version of node
=> fix(*): fix crash on node v18.0 caused by Import Attribute syntax

src/env-cmd.ts, test/env-cmd.spec.ts
Closes #149, Closes #134, Closes #283
There is now a helpful error if you run `env-cmd` on its own, without any associated command. (for example: `env-cmd && node ....`)
The current error is "[ERR_INVALID_ARG_TYPE](https://github.com/toddbluhm/env-cmd/issues/149)" which is quite cryptic
=> feat(cli): provide a more helpful error if there's no command

src/parse-env-file.ts, test/parse-env-file.spec.ts, test/test-files/test
Closes #272
Because of #393, the next release will already be a potential breaking change for `.env.*` files that include a `#` symbol on the same line as key/value pair.
So, this might be a good opportunity to resolve another long-standing inconsistency between this repository and other `.env` tools. Specifically: **inline comment support**.
Tools/libraries that support inline comments in `.env` files:
- [dotenv](https://github.com/motdotla/dotenv/pull/568)
- [phpdotenv](https://github.com/vlucas/phpdotenv#comments)
- [dotenvx](https://github.com/dotenvx/dotenvx)
- [the unofficial spec](https://hexdocs.pm/dotenvy/dotenv-file-format.html#comments)
- [GitHub.com's default syntax highlighting](https://github.com/github-linguist/linguist/blob/5fad8d57605a914026a65b0e3ff6815d739944de/lib/lingu …
=> feat: parse inline comments

dist/expand-envs.js, dist/parse-env-file.js, src/expand-envs.ts, src/parse-env-file.ts
we don't use a [lockfile](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json) in this repository (see 727f429 ), so the CI could start failing despite nothing changing in this repo.
The current failures are because this line:
https://github.com/toddbluhm/env-cmd/blob/adf1934f01074ec2a97b5f975d439faef99c96a2/package.json#L76
...now resolves to `v8.39.0`, and one of the recent updates in that package included breaking changes
=> chore: fix CI failing on the master branch

CHANGELOG.md
Update the `CHANGELOG` to document another breaking change that was made in `11.0.0`
=> Update changelog with additional breaking change
